//nolint:misspell // ventas vocabulary is Spanish per project convention.
package outbound

import (
	"context"
	"time"
)

// MicrosipClienteInput is the input value object for MicrosipClienteWriter.Crear.
// Snapshot data comes from the venta; catálogo defaults come from cliente_defaults.go.
type MicrosipClienteInput struct {
	Nombre                  string
	Telefono                *string
	Calle                   string
	NumeroExterior          *string
	Colonia                 string
	Poblacion               string
	CodigoPostal            *string
	Referencia              *string // → LIBRES_CLIENTES.REFERENCIA
	Latitud                 *string // → LIBRES_CLIENTES.U_LATITUD
	Longitud                *string // → LIBRES_CLIENTES.U_LONGITUD
	ZonaClienteID           int
	CobradorID              int // -1 when zona has none
	VendedorID              int // -1 when zona has none
	CiudadID                int
	EstadoID                int
	PaisID                  int
	CondPagoID              int
	TipoClienteID           int
	MonedaID                int
	ViaEmbarqueID           int
	ComprobanteDomicilioID  int
	IdentificacionOficialID int
}

// MicrosipClienteResult returns the IDs generated by Microsip.
type MicrosipClienteResult struct {
	ClienteID    int
	DirCliID     int
	ClaveCliente string // e.g. "0044523"
}

// MicrosipClienteWriter persists a new cliente in Microsip CLIENTES
// (+ DIRS_CLIENTES + CLAVES_CLIENTES + LIBRES_CLIENTES) atomically. Must be
// called inside an open Firebird transaction — joins via
// firebird.GetQuerier(ctx, pool.DB).
type MicrosipClienteWriter interface {
	Crear(ctx context.Context, in MicrosipClienteInput) (MicrosipClienteResult, error)

	// ReactivarSiEnBaja flips CLIENTES.ESTATUS from 'B' (baja) to 'A' (activo)
	// for clienteID, stamping USUARIO_ULT_MODIF / FECHA_HORA_ULT_MODIF with the
	// given now. Idempotent: the underlying UPDATE guards on ESTATUS='B', so
	// calling this on a cliente that is already 'A' (or any other estatus) is a
	// no-op — reactivado reports false and no columns are touched. Must be
	// called inside an open Firebird transaction — joins via
	// firebird.GetQuerier(ctx, pool.DB). Does NOT touch FECHA_SUSP/CAUSA_SUSP;
	// Microsip keeps those as suspension history even after reactivation.
	ReactivarSiEnBaja(ctx context.Context, clienteID int, now time.Time) (reactivado bool, err error)
}
