-- ============================================================================
-- Down 000016: deshace outbox de MSP_PAGOS_RECIBIDOS + drop MSP_PAGOS_IMAGENES
-- ============================================================================
-- El backfill ESTADO='A'/RECEIVED_AT/APLICADO_AT/UPDATED_AT no se deshace: una
-- vez quitada la columna no hay forma de saber qué filas eran originales y
-- cuáles backfilleadas. Reaplicar la up vuelve a poner ESTADO='A' en todo
-- lo que esté con ESTADO IS NULL, que es justo lo que necesitamos.

-- ─── DROP MSP_PAGOS_IMAGENES ─────────────────────────────────────────────────
DROP INDEX IDX_MSP_PAGOS_IMG_PAGO;
DROP TABLE MSP_PAGOS_IMAGENES;

COMMIT;

-- ─── Quitar índices del outbox ───────────────────────────────────────────────
DROP INDEX IDX_MSP_PAGOS_REC_ESTADO;
DROP INDEX IDX_MSP_PAGOS_REC_CARGO;
DROP INDEX IDX_MSP_PAGOS_REC_PEND;

COMMIT;

-- ─── Reponer NOT NULL en DOCTO_CC_ID antes de drop ESTADO ────────────────────
-- Si quedan pendientes con DOCTO_CC_ID NULL truena la migración hacia atrás;
-- ese es el comportamiento deseado (no perdemos pagos sin aplicar).

ALTER TABLE MSP_PAGOS_RECIBIDOS ALTER COLUMN DOCTO_CC_ID   SET NOT NULL;
ALTER TABLE MSP_PAGOS_RECIBIDOS ALTER COLUMN UPDATED_AT    DROP NOT NULL;
ALTER TABLE MSP_PAGOS_RECIBIDOS ALTER COLUMN RECEIVED_AT   DROP NOT NULL;
ALTER TABLE MSP_PAGOS_RECIBIDOS ALTER COLUMN INTENTOS      DROP NOT NULL;
ALTER TABLE MSP_PAGOS_RECIBIDOS ALTER COLUMN ESTADO        DROP NOT NULL;

COMMIT;

-- ─── Drop columnas en orden inverso ──────────────────────────────────────────
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP UPDATED_AT;
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP UPDATED_BY;
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP CREATED_BY;
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP APLICADO_AT;
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP RECEIVED_AT;
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP FOLIO;
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP IMPTE_DOCTO_CC_ID;
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP ULTIMO_ERROR;
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP INTENTOS;
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP ESTADO;
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP LON;
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP LAT;
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP CONCEPTO_CC_ID;
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP FORMA_COBRO_ID;
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP IMPORTE;
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP COBRADOR;
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP COBRADOR_ID;
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP CLIENTE_ID;
ALTER TABLE MSP_PAGOS_RECIBIDOS DROP CARGO_DOCTO_CC_ID;

COMMIT;

-- ─── Registro ────────────────────────────────────────────────────────────────
DELETE FROM MSP_MIGRATIONS WHERE ID = 16;
COMMIT;
