-- ============================================================================
-- Migración 000002: VENTAS (módulo de venta en ruta / camioneta)
-- ============================================================================
-- Crea:
--   - MSP_VENTAS                (header)
--   - MSP_VENTAS_COMBOS         (combos — antes que productos para FK)
--   - MSP_VENTAS_PRODUCTOS      (líneas de la venta)
--   - MSP_VENTAS_VENDEDORES     (snapshot del equipo)
--   - MSP_VENTAS_IMAGENES       (evidencias / fotos)
--
-- Requiere: migración 000001 aplicada (MSP_USUARIOS debe existir).
-- ============================================================================

-- ─── Header de la venta ────────────────────────────────────────────────────
CREATE TABLE MSP_VENTAS (
  ID                       CHAR(36) CHARACTER SET ASCII NOT NULL,

  -- Cliente (snapshot)
  NOMBRE_CLIENTE           VARCHAR(200) CHARACTER SET ISO8859_1 NOT NULL,
  TELEFONO                 VARCHAR(30)  CHARACTER SET ASCII,
  AVAL_O_RESPONSABLE       VARCHAR(200) CHARACTER SET ISO8859_1,

  -- Dirección estructurada
  CALLE                    VARCHAR(300) CHARACTER SET ISO8859_1 NOT NULL,
  NUMERO_EXTERIOR          VARCHAR(20)  CHARACTER SET ISO8859_1,
  COLONIA                  VARCHAR(120) CHARACTER SET ISO8859_1 NOT NULL,
  POBLACION                VARCHAR(120) CHARACTER SET ISO8859_1 NOT NULL,
  CIUDAD                   VARCHAR(120) CHARACTER SET ISO8859_1 NOT NULL,
  ZONA_CLIENTE_ID          INTEGER,
  LATITUD                  DOUBLE PRECISION NOT NULL,
  LONGITUD                 DOUBLE PRECISION NOT NULL,

  -- Almacenes
  ALMACEN_ORIGEN_ID        INTEGER NOT NULL,
  ALMACEN_DESTINO_ID       INTEGER NOT NULL,

  -- Datos comerciales
  FECHA_VENTA              TIMESTAMP NOT NULL,
  TIPO_VENTA               VARCHAR(20) CHARACTER SET ASCII NOT NULL,

  -- Tres montos snapshot (anual / corto plazo / contado)
  MONTO_ANUAL              NUMERIC(14,2) NOT NULL,
  MONTO_CORTO_PLAZO        NUMERIC(14,2) NOT NULL,
  MONTO_CONTADO            NUMERIC(14,2) NOT NULL,

  -- Plan de crédito (sólo cuando TIPO_VENTA = 'CREDITO')
  PLAZO_MESES              INTEGER,
  ENGANCHE                 NUMERIC(14,2),
  PARCIALIDAD              NUMERIC(14,2),
  FREC_PAGO                VARCHAR(10) CHARACTER SET ASCII,
  DIA_COBRANZA_SEMANA      VARCHAR(10) CHARACTER SET ASCII,
  DIA_COBRANZA_MES         SMALLINT,

  NOTA                     VARCHAR(500) CHARACTER SET ISO8859_1,

  -- Auditoría
  CREATED_AT               TIMESTAMP NOT NULL,
  UPDATED_AT               TIMESTAMP NOT NULL,
  CREATED_BY               CHAR(36) CHARACTER SET ASCII NOT NULL,
  UPDATED_BY               CHAR(36) CHARACTER SET ASCII NOT NULL,

  -- Soft cancel
  CANCELED_AT              TIMESTAMP,
  CANCELED_BY              CHAR(36) CHARACTER SET ASCII,
  CANCEL_REASON            VARCHAR(500) CHARACTER SET ISO8859_1,

  CONSTRAINT PK_MSP_VENTAS PRIMARY KEY (ID),

  CONSTRAINT FK_MSP_VENTAS_CREATED_BY  FOREIGN KEY (CREATED_BY)  REFERENCES MSP_USUARIOS (ID),
  CONSTRAINT FK_MSP_VENTAS_UPDATED_BY  FOREIGN KEY (UPDATED_BY)  REFERENCES MSP_USUARIOS (ID),
  CONSTRAINT FK_MSP_VENTAS_CANCELED_BY FOREIGN KEY (CANCELED_BY) REFERENCES MSP_USUARIOS (ID),

  CONSTRAINT CK_MSP_VENTAS_TIPO_VENTA CHECK (
    TIPO_VENTA IN ('CONTADO', 'CREDITO')
  ),

  CONSTRAINT CK_MSP_VENTAS_FREC_PAGO CHECK (
    FREC_PAGO IS NULL OR FREC_PAGO IN ('SEMANAL', 'QUINCENAL', 'MENSUAL')
  ),

  CONSTRAINT CK_MSP_VENTAS_DIA_SEMANA CHECK (
    DIA_COBRANZA_SEMANA IS NULL
    OR DIA_COBRANZA_SEMANA IN ('LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO','DOMINGO')
  ),

  CONSTRAINT CK_MSP_VENTAS_DIA_MES CHECK (
    DIA_COBRANZA_MES IS NULL OR (DIA_COBRANZA_MES BETWEEN 1 AND 31)
  ),

  -- CONTADO: sin plan; CREDITO: plan + parcialidad obligatorios
  CONSTRAINT CK_MSP_VENTAS_TIPO_CREDITO_COHERENTE CHECK (
    (TIPO_VENTA = 'CONTADO'
      AND FREC_PAGO IS NULL
      AND DIA_COBRANZA_SEMANA IS NULL
      AND DIA_COBRANZA_MES IS NULL
      AND PLAZO_MESES IS NULL
      AND ENGANCHE IS NULL
      AND PARCIALIDAD IS NULL)
    OR
    (TIPO_VENTA = 'CREDITO'
      AND FREC_PAGO IS NOT NULL
      AND PLAZO_MESES IS NOT NULL
      AND PARCIALIDAD IS NOT NULL)
  ),

  -- SEMANAL → día de semana; QUINCENAL/MENSUAL → uno u otro (semana o mes)
  CONSTRAINT CK_MSP_VENTAS_DIA_COBRANZA_COHERENTE CHECK (
    FREC_PAGO IS NULL
    OR (FREC_PAGO = 'SEMANAL'
         AND DIA_COBRANZA_SEMANA IS NOT NULL
         AND DIA_COBRANZA_MES IS NULL)
    OR (FREC_PAGO IN ('QUINCENAL', 'MENSUAL')
         AND ((DIA_COBRANZA_SEMANA IS NOT NULL AND DIA_COBRANZA_MES IS NULL)
              OR (DIA_COBRANZA_SEMANA IS NULL AND DIA_COBRANZA_MES IS NOT NULL)))
  ),

  CONSTRAINT CK_MSP_VENTAS_CANCEL_COHERENTE CHECK (
    (CANCELED_AT IS NULL  AND CANCELED_BY IS NULL)
    OR (CANCELED_AT IS NOT NULL AND CANCELED_BY IS NOT NULL)
  ),

  CONSTRAINT CK_MSP_VENTAS_LATITUD  CHECK (LATITUD  BETWEEN -90  AND 90),
  CONSTRAINT CK_MSP_VENTAS_LONGITUD CHECK (LONGITUD BETWEEN -180 AND 180),

  CONSTRAINT CK_MSP_VENTAS_MONTO_ANUAL_NONNEG    CHECK (MONTO_ANUAL       >= 0),
  CONSTRAINT CK_MSP_VENTAS_MONTO_CORTOPL_NONNEG  CHECK (MONTO_CORTO_PLAZO >= 0),
  CONSTRAINT CK_MSP_VENTAS_MONTO_CONTADO_NONNEG  CHECK (MONTO_CONTADO     >= 0),
  CONSTRAINT CK_MSP_VENTAS_PARCIALIDAD_NONNEG    CHECK (PARCIALIDAD IS NULL OR PARCIALIDAD >= 0),
  CONSTRAINT CK_MSP_VENTAS_ENGANCHE_NONNEG       CHECK (ENGANCHE IS NULL OR ENGANCHE >= 0),
  CONSTRAINT CK_MSP_VENTAS_PLAZO_POSITIVO        CHECK (PLAZO_MESES IS NULL OR PLAZO_MESES > 0)
);

CREATE DESCENDING INDEX IDX_MSP_VENTAS_FECHA_VENTA ON MSP_VENTAS (FECHA_VENTA);
CREATE INDEX            IDX_MSP_VENTAS_CREATED_BY   ON MSP_VENTAS (CREATED_BY);
CREATE INDEX            IDX_MSP_VENTAS_ALMACEN_ORG  ON MSP_VENTAS (ALMACEN_ORIGEN_ID);
CREATE INDEX            IDX_MSP_VENTAS_ZONA_CLIENTE ON MSP_VENTAS (ZONA_CLIENTE_ID);
CREATE INDEX            IDX_MSP_VENTAS_TIPO_VENTA   ON MSP_VENTAS (TIPO_VENTA);
CREATE INDEX            IDX_MSP_VENTAS_CANCELED_AT  ON MSP_VENTAS (CANCELED_AT);

-- ─── Combos (definidos antes que productos por dependencia de FK) ─────────
CREATE TABLE MSP_VENTAS_COMBOS (
  ID                  CHAR(36) CHARACTER SET ASCII NOT NULL,
  VENTA_ID            CHAR(36) CHARACTER SET ASCII NOT NULL,
  NOMBRE_COMBO        VARCHAR(200) CHARACTER SET ISO8859_1 NOT NULL,
  PRECIO_ANUAL        NUMERIC(14,2) NOT NULL,
  PRECIO_CORTO_PLAZO  NUMERIC(14,2) NOT NULL,
  PRECIO_CONTADO      NUMERIC(14,2) NOT NULL,
  CREATED_AT          TIMESTAMP NOT NULL,
  UPDATED_AT          TIMESTAMP NOT NULL,
  CREATED_BY          CHAR(36) CHARACTER SET ASCII NOT NULL,
  UPDATED_BY          CHAR(36) CHARACTER SET ASCII NOT NULL,

  CONSTRAINT PK_MSP_VENTAS_COMBOS PRIMARY KEY (ID),
  CONSTRAINT FK_MSP_VENTAS_COMBOS_VENTA      FOREIGN KEY (VENTA_ID)   REFERENCES MSP_VENTAS    (ID),
  CONSTRAINT FK_MSP_VENTAS_COMBOS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES MSP_USUARIOS (ID),
  CONSTRAINT FK_MSP_VENTAS_COMBOS_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES MSP_USUARIOS (ID),

  CONSTRAINT CK_MSP_VENTAS_COMBOS_PRECIO_ANUAL    CHECK (PRECIO_ANUAL       >= 0),
  CONSTRAINT CK_MSP_VENTAS_COMBOS_PRECIO_CORTOPL  CHECK (PRECIO_CORTO_PLAZO >= 0),
  CONSTRAINT CK_MSP_VENTAS_COMBOS_PRECIO_CONTADO  CHECK (PRECIO_CONTADO     >= 0)
);

CREATE INDEX IDX_MSP_VENTAS_COMBOS_VENTA ON MSP_VENTAS_COMBOS (VENTA_ID);

-- ─── Productos (líneas de venta) ──────────────────────────────────────────
CREATE TABLE MSP_VENTAS_PRODUCTOS (
  ID                  CHAR(36) CHARACTER SET ASCII NOT NULL,
  VENTA_ID            CHAR(36) CHARACTER SET ASCII NOT NULL,
  ARTICULO_ID         INTEGER NOT NULL,
  ARTICULO            VARCHAR(200) CHARACTER SET ISO8859_1 NOT NULL,
  CANTIDAD            NUMERIC(10,4) NOT NULL,
  PRECIO_ANUAL        NUMERIC(14,2) NOT NULL,
  PRECIO_CORTO_PLAZO  NUMERIC(14,2) NOT NULL,
  PRECIO_CONTADO      NUMERIC(14,2) NOT NULL,
  COMBO_ID            CHAR(36) CHARACTER SET ASCII,
  CREATED_AT          TIMESTAMP NOT NULL,
  UPDATED_AT          TIMESTAMP NOT NULL,
  CREATED_BY          CHAR(36) CHARACTER SET ASCII NOT NULL,
  UPDATED_BY          CHAR(36) CHARACTER SET ASCII NOT NULL,

  CONSTRAINT PK_MSP_VENTAS_PRODUCTOS PRIMARY KEY (ID),
  CONSTRAINT FK_MSP_VENTAS_PRODUCTOS_VENTA      FOREIGN KEY (VENTA_ID)   REFERENCES MSP_VENTAS         (ID),
  CONSTRAINT FK_MSP_VENTAS_PRODUCTOS_COMBO      FOREIGN KEY (COMBO_ID)   REFERENCES MSP_VENTAS_COMBOS  (ID),
  CONSTRAINT FK_MSP_VENTAS_PRODUCTOS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES MSP_USUARIOS       (ID),
  CONSTRAINT FK_MSP_VENTAS_PRODUCTOS_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES MSP_USUARIOS       (ID),

  CONSTRAINT CK_MSP_VENTAS_PRODUCTOS_CANTIDAD_POS    CHECK (CANTIDAD > 0),
  CONSTRAINT CK_MSP_VENTAS_PRODUCTOS_PRECIO_ANUAL    CHECK (PRECIO_ANUAL       >= 0),
  CONSTRAINT CK_MSP_VENTAS_PRODUCTOS_PRECIO_CORTOPL  CHECK (PRECIO_CORTO_PLAZO >= 0),
  CONSTRAINT CK_MSP_VENTAS_PRODUCTOS_PRECIO_CONTADO  CHECK (PRECIO_CONTADO     >= 0)
);

CREATE INDEX IDX_MSP_VENTAS_PRODUCTOS_VENTA    ON MSP_VENTAS_PRODUCTOS (VENTA_ID);
CREATE INDEX IDX_MSP_VENTAS_PRODUCTOS_ARTICULO ON MSP_VENTAS_PRODUCTOS (ARTICULO_ID);
CREATE INDEX IDX_MSP_VENTAS_PRODUCTOS_COMBO    ON MSP_VENTAS_PRODUCTOS (COMBO_ID);

-- ─── Vendedores (snapshot del equipo) ─────────────────────────────────────
CREATE TABLE MSP_VENTAS_VENDEDORES (
  ID                     CHAR(36) CHARACTER SET ASCII NOT NULL,
  VENTA_ID               CHAR(36) CHARACTER SET ASCII NOT NULL,
  VENDEDOR_USUARIO_ID    CHAR(36) CHARACTER SET ASCII NOT NULL,
  VENDEDOR_EMAIL         VARCHAR(255) CHARACTER SET ASCII NOT NULL,
  VENDEDOR_NOMBRE        VARCHAR(200) CHARACTER SET ISO8859_1 NOT NULL,
  CREATED_AT             TIMESTAMP NOT NULL,
  UPDATED_AT             TIMESTAMP NOT NULL,
  CREATED_BY             CHAR(36) CHARACTER SET ASCII NOT NULL,
  UPDATED_BY             CHAR(36) CHARACTER SET ASCII NOT NULL,

  CONSTRAINT PK_MSP_VENTAS_VENDEDORES PRIMARY KEY (ID),
  CONSTRAINT UQ_MSP_VENTAS_VENDEDORES_VENTA_USR  UNIQUE (VENTA_ID, VENDEDOR_USUARIO_ID),
  CONSTRAINT FK_MSP_VENTAS_VENDEDORES_VENTA      FOREIGN KEY (VENTA_ID)            REFERENCES MSP_VENTAS    (ID),
  CONSTRAINT FK_MSP_VENTAS_VENDEDORES_USUARIO    FOREIGN KEY (VENDEDOR_USUARIO_ID) REFERENCES MSP_USUARIOS (ID),
  CONSTRAINT FK_MSP_VENTAS_VENDEDORES_CREATED_BY FOREIGN KEY (CREATED_BY)          REFERENCES MSP_USUARIOS (ID),
  CONSTRAINT FK_MSP_VENTAS_VENDEDORES_UPDATED_BY FOREIGN KEY (UPDATED_BY)          REFERENCES MSP_USUARIOS (ID)
);

CREATE INDEX IDX_MSP_VENTAS_VENDEDORES_VENTA   ON MSP_VENTAS_VENDEDORES (VENTA_ID);
CREATE INDEX IDX_MSP_VENTAS_VENDEDORES_USUARIO ON MSP_VENTAS_VENDEDORES (VENDEDOR_USUARIO_ID);
CREATE INDEX IDX_MSP_VENTAS_VENDEDORES_EMAIL   ON MSP_VENTAS_VENDEDORES (VENDEDOR_EMAIL);

-- ─── Imágenes (evidencia, comprobantes) ───────────────────────────────────
CREATE TABLE MSP_VENTAS_IMAGENES (
  ID                CHAR(36) CHARACTER SET ASCII NOT NULL,
  VENTA_ID          CHAR(36) CHARACTER SET ASCII NOT NULL,
  STORAGE_KIND      VARCHAR(20)  CHARACTER SET ASCII NOT NULL,
  STORAGE_KEY       VARCHAR(500) CHARACTER SET ASCII NOT NULL,
  MIME              VARCHAR(100) CHARACTER SET ASCII NOT NULL,
  SIZE_BYTES        BIGINT NOT NULL,
  DESCRIPCION       VARCHAR(200) CHARACTER SET ISO8859_1,
  CREATED_AT        TIMESTAMP NOT NULL,
  UPDATED_AT        TIMESTAMP NOT NULL,
  CREATED_BY        CHAR(36) CHARACTER SET ASCII NOT NULL,
  UPDATED_BY        CHAR(36) CHARACTER SET ASCII NOT NULL,

  CONSTRAINT PK_MSP_VENTAS_IMAGENES PRIMARY KEY (ID),
  CONSTRAINT FK_MSP_VENTAS_IMAGENES_VENTA      FOREIGN KEY (VENTA_ID)   REFERENCES MSP_VENTAS    (ID),
  CONSTRAINT FK_MSP_VENTAS_IMAGENES_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES MSP_USUARIOS (ID),
  CONSTRAINT FK_MSP_VENTAS_IMAGENES_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES MSP_USUARIOS (ID),

  CONSTRAINT CK_MSP_VENTAS_IMAGENES_STORAGE_KIND CHECK (
    STORAGE_KIND IN ('FILESYSTEM', 'R2')
  ),
  CONSTRAINT CK_MSP_VENTAS_IMAGENES_SIZE_NONNEG CHECK (
    SIZE_BYTES >= 0
  ),
  CONSTRAINT CK_MSP_VENTAS_IMAGENES_MIME_VALID CHECK (
    MIME IN ('image/jpeg', 'image/png', 'image/gif', 'image/webp')
  )
);

CREATE INDEX IDX_MSP_VENTAS_IMAGENES_VENTA   ON MSP_VENTAS_IMAGENES (VENTA_ID);
CREATE INDEX IDX_MSP_VENTAS_IMAGENES_STORAGE ON MSP_VENTAS_IMAGENES (STORAGE_KIND);

-- ─── Registrar la migración como aplicada ──────────────────────────────────
INSERT INTO MSP_MIGRATIONS (ID, NAME, APPLIED_AT)
VALUES (2, '000002_create_ventas_tables', CURRENT_TIMESTAMP);

COMMIT;
