DROP INDEX IDX_MSP_FAILED_INTENTS_REQUEST_ID;
DROP INDEX IDX_MSP_FAILED_INTENTS_FB_UID;
DROP INDEX IDX_MSP_FAILED_INTENTS_STATUS;
DROP INDEX IDX_MSP_FAILED_INTENTS_RECEIVED;
COMMIT;

DROP TABLE MSP_FAILED_INTENTS;
COMMIT;

DELETE FROM MSP_MIGRATIONS WHERE ID = 31;
COMMIT;
