-- Revert 000034: eliminar REVERSADO de MSP_VENTAS_TRASPASOS.
--
-- El orden es el inverso exacto de la migración up:
--   1. DROP INDEX (depende de la columna).
--   2. DROP CONSTRAINT CHECK (depende de la columna).
--   3. DROP COLUMN.

DROP INDEX IDX_MSP_VTA_TRASP_REVERSADO;
COMMIT;

ALTER TABLE MSP_VENTAS_TRASPASOS DROP CONSTRAINT CK_MSP_VTA_TRASP_REVERSADO;
COMMIT;

ALTER TABLE MSP_VENTAS_TRASPASOS DROP REVERSADO;
COMMIT;

DELETE FROM MSP_MIGRATIONS WHERE ID = 34;
COMMIT;
