-- Reverse de 000004: quita POSICION de los hijos.
ALTER TABLE MSP_VENTAS_PRODUCTOS DROP CONSTRAINT UQ_MSP_VENTAS_PRODS_VENTA_POS;
ALTER TABLE MSP_VENTAS_PRODUCTOS DROP CONSTRAINT CK_VTA_PROD_POSICION_POS;
ALTER TABLE MSP_VENTAS_PRODUCTOS DROP POSICION;

ALTER TABLE MSP_VENTAS_COMBOS DROP CONSTRAINT UQ_MSP_VENTAS_COMBOS_VENTA_POS;
ALTER TABLE MSP_VENTAS_COMBOS DROP CONSTRAINT CK_VTA_CMB_POSICION_POS;
ALTER TABLE MSP_VENTAS_COMBOS DROP POSICION;

ALTER TABLE MSP_VENTAS_VENDEDORES DROP CONSTRAINT UQ_MSP_VENTAS_VEND_VENTA_POS;
ALTER TABLE MSP_VENTAS_VENDEDORES DROP CONSTRAINT CK_MSP_VENTAS_VEND_POSICION_POS;
ALTER TABLE MSP_VENTAS_VENDEDORES DROP POSICION;

DELETE FROM MSP_MIGRATIONS WHERE ID = 4;

COMMIT;
