-- Down for 000052_grant_msp_generators_to_microsip_users
-- Revokes the PUBLIC generator grants added in the up migration.

REVOKE USAGE ON GENERATOR GEN_MSP_SALDOS_ERRORS_ID FROM PUBLIC;
REVOKE USAGE ON GENERATOR GEN_MSP_PAGOS_CHANGELOG_SEQ FROM PUBLIC;
REVOKE USAGE ON GENERATOR GEN_MSP_SALDOS_CHANGELOG_SEQ FROM PUBLIC;
COMMIT;

DELETE FROM MSP_MIGRATIONS WHERE ID = 52;
COMMIT;
