-- ============================================================================
-- Migración 000005: columnas de texto en MSP_* pasan de ISO8859_1 a UTF8
-- ============================================================================
-- Bugs A+B (encoding boundary) se resuelven aquí. Detalles en
-- docs/module-standards/ENCODING_HANDLING.md.
--
-- Firebird no soporta cambiar el CHARACTER SET de una columna in-place via
-- ALTER COLUMN TYPE — ese statement existe pero ignora silenciosamente la
-- cláusula CHARACTER SET. La única manera limpia es el patrón trampolín:
--
--   1) ADD <col>_NEW VARCHAR(N) CHARACTER SET UTF8
--   2) UPDATE T SET <col>_NEW = <col>    -- server-side transliterar ISO8859_1→UTF8
--   3) DROP <col>
--   4) RENAME <col>_NEW TO <col>
--   5) Re-aplicar NOT NULL si la columna lo tenía
--
-- Las tablas que pertenecen a Microsip (CLIENTES, ARTICULOS, COBROS, etc.) NO
-- se tocan. La conexión del driver pasa a charset=UTF8; Firebird transliterar
-- automáticamente al leer/escribir columnas con otros charsets.
-- ============================================================================

-- ─── helper macro nota ───────────────────────────────────────────────────────
-- Cada bloque sigue: ADD _NEW (UTF8) → UPDATE copy → DROP old → RENAME → SET NOT NULL si aplica.

-- ─── MSP_VENTAS ─────────────────────────────────────────────────────────────

-- NOMBRE_CLIENTE — NOT NULL
ALTER TABLE MSP_VENTAS ADD NOMBRE_CLIENTE_NEW VARCHAR(200) CHARACTER SET UTF8;
UPDATE MSP_VENTAS SET NOMBRE_CLIENTE_NEW = NOMBRE_CLIENTE;
ALTER TABLE MSP_VENTAS DROP NOMBRE_CLIENTE;
ALTER TABLE MSP_VENTAS ALTER COLUMN NOMBRE_CLIENTE_NEW TO NOMBRE_CLIENTE;
ALTER TABLE MSP_VENTAS ALTER COLUMN NOMBRE_CLIENTE SET NOT NULL;

-- AVAL_O_RESPONSABLE — nullable
ALTER TABLE MSP_VENTAS ADD AVAL_O_RESPONSABLE_NEW VARCHAR(200) CHARACTER SET UTF8;
UPDATE MSP_VENTAS SET AVAL_O_RESPONSABLE_NEW = AVAL_O_RESPONSABLE;
ALTER TABLE MSP_VENTAS DROP AVAL_O_RESPONSABLE;
ALTER TABLE MSP_VENTAS ALTER COLUMN AVAL_O_RESPONSABLE_NEW TO AVAL_O_RESPONSABLE;

-- CALLE — NOT NULL
ALTER TABLE MSP_VENTAS ADD CALLE_NEW VARCHAR(300) CHARACTER SET UTF8;
UPDATE MSP_VENTAS SET CALLE_NEW = CALLE;
ALTER TABLE MSP_VENTAS DROP CALLE;
ALTER TABLE MSP_VENTAS ALTER COLUMN CALLE_NEW TO CALLE;
ALTER TABLE MSP_VENTAS ALTER COLUMN CALLE SET NOT NULL;

-- NUMERO_EXTERIOR — nullable
ALTER TABLE MSP_VENTAS ADD NUMERO_EXTERIOR_NEW VARCHAR(20) CHARACTER SET UTF8;
UPDATE MSP_VENTAS SET NUMERO_EXTERIOR_NEW = NUMERO_EXTERIOR;
ALTER TABLE MSP_VENTAS DROP NUMERO_EXTERIOR;
ALTER TABLE MSP_VENTAS ALTER COLUMN NUMERO_EXTERIOR_NEW TO NUMERO_EXTERIOR;

-- COLONIA — NOT NULL
ALTER TABLE MSP_VENTAS ADD COLONIA_NEW VARCHAR(120) CHARACTER SET UTF8;
UPDATE MSP_VENTAS SET COLONIA_NEW = COLONIA;
ALTER TABLE MSP_VENTAS DROP COLONIA;
ALTER TABLE MSP_VENTAS ALTER COLUMN COLONIA_NEW TO COLONIA;
ALTER TABLE MSP_VENTAS ALTER COLUMN COLONIA SET NOT NULL;

-- POBLACION — NOT NULL
ALTER TABLE MSP_VENTAS ADD POBLACION_NEW VARCHAR(120) CHARACTER SET UTF8;
UPDATE MSP_VENTAS SET POBLACION_NEW = POBLACION;
ALTER TABLE MSP_VENTAS DROP POBLACION;
ALTER TABLE MSP_VENTAS ALTER COLUMN POBLACION_NEW TO POBLACION;
ALTER TABLE MSP_VENTAS ALTER COLUMN POBLACION SET NOT NULL;

-- CIUDAD — NOT NULL
ALTER TABLE MSP_VENTAS ADD CIUDAD_NEW VARCHAR(120) CHARACTER SET UTF8;
UPDATE MSP_VENTAS SET CIUDAD_NEW = CIUDAD;
ALTER TABLE MSP_VENTAS DROP CIUDAD;
ALTER TABLE MSP_VENTAS ALTER COLUMN CIUDAD_NEW TO CIUDAD;
ALTER TABLE MSP_VENTAS ALTER COLUMN CIUDAD SET NOT NULL;

-- NOTA — nullable
ALTER TABLE MSP_VENTAS ADD NOTA_NEW VARCHAR(500) CHARACTER SET UTF8;
UPDATE MSP_VENTAS SET NOTA_NEW = NOTA;
ALTER TABLE MSP_VENTAS DROP NOTA;
ALTER TABLE MSP_VENTAS ALTER COLUMN NOTA_NEW TO NOTA;

-- CANCEL_REASON — nullable
ALTER TABLE MSP_VENTAS ADD CANCEL_REASON_NEW VARCHAR(500) CHARACTER SET UTF8;
UPDATE MSP_VENTAS SET CANCEL_REASON_NEW = CANCEL_REASON;
ALTER TABLE MSP_VENTAS DROP CANCEL_REASON;
ALTER TABLE MSP_VENTAS ALTER COLUMN CANCEL_REASON_NEW TO CANCEL_REASON;

-- ─── MSP_VENTAS_COMBOS ──────────────────────────────────────────────────────

-- NOMBRE_COMBO — NOT NULL
ALTER TABLE MSP_VENTAS_COMBOS ADD NOMBRE_COMBO_NEW VARCHAR(200) CHARACTER SET UTF8;
UPDATE MSP_VENTAS_COMBOS SET NOMBRE_COMBO_NEW = NOMBRE_COMBO;
ALTER TABLE MSP_VENTAS_COMBOS DROP NOMBRE_COMBO;
ALTER TABLE MSP_VENTAS_COMBOS ALTER COLUMN NOMBRE_COMBO_NEW TO NOMBRE_COMBO;
ALTER TABLE MSP_VENTAS_COMBOS ALTER COLUMN NOMBRE_COMBO SET NOT NULL;

-- ─── MSP_VENTAS_PRODUCTOS ───────────────────────────────────────────────────

-- ARTICULO — NOT NULL
ALTER TABLE MSP_VENTAS_PRODUCTOS ADD ARTICULO_NEW VARCHAR(200) CHARACTER SET UTF8;
UPDATE MSP_VENTAS_PRODUCTOS SET ARTICULO_NEW = ARTICULO;
ALTER TABLE MSP_VENTAS_PRODUCTOS DROP ARTICULO;
ALTER TABLE MSP_VENTAS_PRODUCTOS ALTER COLUMN ARTICULO_NEW TO ARTICULO;
ALTER TABLE MSP_VENTAS_PRODUCTOS ALTER COLUMN ARTICULO SET NOT NULL;

-- ─── MSP_VENTAS_VENDEDORES ──────────────────────────────────────────────────

-- VENDEDOR_NOMBRE — NOT NULL
ALTER TABLE MSP_VENTAS_VENDEDORES ADD VENDEDOR_NOMBRE_NEW VARCHAR(200) CHARACTER SET UTF8;
UPDATE MSP_VENTAS_VENDEDORES SET VENDEDOR_NOMBRE_NEW = VENDEDOR_NOMBRE;
ALTER TABLE MSP_VENTAS_VENDEDORES DROP VENDEDOR_NOMBRE;
ALTER TABLE MSP_VENTAS_VENDEDORES ALTER COLUMN VENDEDOR_NOMBRE_NEW TO VENDEDOR_NOMBRE;
ALTER TABLE MSP_VENTAS_VENDEDORES ALTER COLUMN VENDEDOR_NOMBRE SET NOT NULL;

-- ─── MSP_VENTAS_IMAGENES ────────────────────────────────────────────────────

-- DESCRIPCION — nullable
ALTER TABLE MSP_VENTAS_IMAGENES ADD DESCRIPCION_NEW VARCHAR(200) CHARACTER SET UTF8;
UPDATE MSP_VENTAS_IMAGENES SET DESCRIPCION_NEW = DESCRIPCION;
ALTER TABLE MSP_VENTAS_IMAGENES DROP DESCRIPCION;
ALTER TABLE MSP_VENTAS_IMAGENES ALTER COLUMN DESCRIPCION_NEW TO DESCRIPCION;

-- ─── MSP_USUARIOS ───────────────────────────────────────────────────────────

-- NOMBRE — NOT NULL
ALTER TABLE MSP_USUARIOS ADD NOMBRE_NEW VARCHAR(200) CHARACTER SET UTF8;
UPDATE MSP_USUARIOS SET NOMBRE_NEW = NOMBRE;
ALTER TABLE MSP_USUARIOS DROP NOMBRE;
ALTER TABLE MSP_USUARIOS ALTER COLUMN NOMBRE_NEW TO NOMBRE;
ALTER TABLE MSP_USUARIOS ALTER COLUMN NOMBRE SET NOT NULL;

-- ─── MSP_ROLES ──────────────────────────────────────────────────────────────

-- NOMBRE — NOT NULL
ALTER TABLE MSP_ROLES ADD NOMBRE_NEW VARCHAR(50) CHARACTER SET UTF8;
UPDATE MSP_ROLES SET NOMBRE_NEW = NOMBRE;
ALTER TABLE MSP_ROLES DROP NOMBRE;
ALTER TABLE MSP_ROLES ALTER COLUMN NOMBRE_NEW TO NOMBRE;
ALTER TABLE MSP_ROLES ALTER COLUMN NOMBRE SET NOT NULL;

-- DESCRIPCION — nullable
ALTER TABLE MSP_ROLES ADD DESCRIPCION_NEW VARCHAR(255) CHARACTER SET UTF8;
UPDATE MSP_ROLES SET DESCRIPCION_NEW = DESCRIPCION;
ALTER TABLE MSP_ROLES DROP DESCRIPCION;
ALTER TABLE MSP_ROLES ALTER COLUMN DESCRIPCION_NEW TO DESCRIPCION;

-- ─── MSP_PERMISOS ───────────────────────────────────────────────────────────

-- DESCRIPCION — NOT NULL
ALTER TABLE MSP_PERMISOS ADD DESCRIPCION_NEW VARCHAR(255) CHARACTER SET UTF8;
UPDATE MSP_PERMISOS SET DESCRIPCION_NEW = DESCRIPCION;
ALTER TABLE MSP_PERMISOS DROP DESCRIPCION;
ALTER TABLE MSP_PERMISOS ALTER COLUMN DESCRIPCION_NEW TO DESCRIPCION;
ALTER TABLE MSP_PERMISOS ALTER COLUMN DESCRIPCION SET NOT NULL;

-- CATEGORIA — NOT NULL + indexed (drop+recreate IDX around trampoline)
DROP INDEX IDX_MSP_PERMISOS_CATEGORIA;
ALTER TABLE MSP_PERMISOS ADD CATEGORIA_NEW VARCHAR(30) CHARACTER SET UTF8;
UPDATE MSP_PERMISOS SET CATEGORIA_NEW = CATEGORIA;
ALTER TABLE MSP_PERMISOS DROP CATEGORIA;
ALTER TABLE MSP_PERMISOS ALTER COLUMN CATEGORIA_NEW TO CATEGORIA;
ALTER TABLE MSP_PERMISOS ALTER COLUMN CATEGORIA SET NOT NULL;
CREATE INDEX IDX_MSP_PERMISOS_CATEGORIA ON MSP_PERMISOS (CATEGORIA);

-- ─── Registro ────────────────────────────────────────────────────────────────
INSERT INTO MSP_MIGRATIONS (ID, NAME, APPLIED_AT)
VALUES (5, '000005_msp_tables_to_utf8', CURRENT_TIMESTAMP);

COMMIT;
