-- ============================================================================
-- Migración 000003: VENTAS staging refactor
-- ============================================================================
-- Cambios:
--   1) MSP_VENTAS: agrega CLIENTE_ID (FK opcional a Microsip CLIENTES).
--   2) MSP_VENTAS: agrega STATUS enum ('borrador' / 'aprobada' / 'cancelada').
--   3) MSP_VENTAS: agrega APPROVED_AT / APPROVED_BY (reservado para flujo
--      futuro de aprobación → push a Microsip).
--   4) MSP_VENTAS_PRODUCTOS: agrega ALMACEN_ORIGEN_ID / ALMACEN_DESTINO_ID
--      (NULL cuando el producto pertenece a un combo; hereda del combo).
--   5) MSP_VENTAS_COMBOS: agrega CANTIDAD + ALMACEN_ORIGEN_ID /
--      ALMACEN_DESTINO_ID (un combo es una unidad física en el camión).
--   6) MSP_VENTAS: elimina ALMACEN_ORIGEN_ID / ALMACEN_DESTINO_ID (movidos a
--      la línea de producto / combo).
--
-- Requiere: migración 000002 aplicada. La FK FK_MSP_VENTAS_CLIENTE apunta a
-- la tabla nativa de Microsip CLIENTES; el dev/prod DB son la misma instancia.
-- ============================================================================

-- ─── 1) MSP_VENTAS: CLIENTE_ID ───────────────────────────────────────────────
ALTER TABLE MSP_VENTAS ADD CLIENTE_ID INTEGER;

ALTER TABLE MSP_VENTAS
  ADD CONSTRAINT FK_MSP_VENTAS_CLIENTE
  FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (CLIENTE_ID);

CREATE INDEX IDX_MSP_VENTAS_CLIENTE_ID ON MSP_VENTAS (CLIENTE_ID);

-- ─── 2) MSP_VENTAS: STATUS ───────────────────────────────────────────────────
-- Sin DEFAULT en DDL (la app pasa el valor en INSERT). Se llena en dos pasos
-- para poder marcar SET NOT NULL después del backfill.
ALTER TABLE MSP_VENTAS ADD STATUS VARCHAR(15) CHARACTER SET ASCII;

UPDATE MSP_VENTAS
   SET STATUS = CASE
       WHEN CANCELED_AT IS NOT NULL THEN 'cancelada'
       ELSE 'borrador'
   END;

ALTER TABLE MSP_VENTAS ALTER COLUMN STATUS SET NOT NULL;

ALTER TABLE MSP_VENTAS
  ADD CONSTRAINT CK_MSP_VENTAS_STATUS
  CHECK (STATUS IN ('borrador', 'aprobada', 'cancelada'));

CREATE INDEX IDX_MSP_VENTAS_STATUS ON MSP_VENTAS (STATUS);

-- ─── 3) MSP_VENTAS: APPROVED_AT / APPROVED_BY ────────────────────────────────
ALTER TABLE MSP_VENTAS ADD APPROVED_AT TIMESTAMP;
ALTER TABLE MSP_VENTAS ADD APPROVED_BY CHAR(36) CHARACTER SET ASCII;

ALTER TABLE MSP_VENTAS
  ADD CONSTRAINT FK_MSP_VENTAS_APPROVED_BY
  FOREIGN KEY (APPROVED_BY) REFERENCES MSP_USUARIOS (ID);

ALTER TABLE MSP_VENTAS
  ADD CONSTRAINT CK_MSP_VENTAS_APPROVED_COHERENTE CHECK (
    (APPROVED_AT IS NULL  AND APPROVED_BY IS NULL)
    OR (APPROVED_AT IS NOT NULL AND APPROVED_BY IS NOT NULL)
  );

-- ─── 4) MSP_VENTAS_PRODUCTOS: ALMACEN_ORIGEN_ID / ALMACEN_DESTINO_ID ─────────
-- Productos sueltos (COMBO_ID IS NULL) heredan los almacenes del header.
-- Productos dentro de un combo se quedan en NULL — heredan del combo.
ALTER TABLE MSP_VENTAS_PRODUCTOS ADD ALMACEN_ORIGEN_ID INTEGER;
ALTER TABLE MSP_VENTAS_PRODUCTOS ADD ALMACEN_DESTINO_ID INTEGER;

UPDATE MSP_VENTAS_PRODUCTOS p
   SET ALMACEN_ORIGEN_ID  = (SELECT v.ALMACEN_ORIGEN_ID  FROM MSP_VENTAS v WHERE v.ID = p.VENTA_ID),
       ALMACEN_DESTINO_ID = (SELECT v.ALMACEN_DESTINO_ID FROM MSP_VENTAS v WHERE v.ID = p.VENTA_ID)
 WHERE p.COMBO_ID IS NULL;

ALTER TABLE MSP_VENTAS_PRODUCTOS
  ADD CONSTRAINT CK_MSP_VENTAS_PRODS_ALMACEN_PRESENCIA CHECK (
    (COMBO_ID IS     NULL AND ALMACEN_ORIGEN_ID IS NOT NULL AND ALMACEN_DESTINO_ID IS NOT NULL)
    OR
    (COMBO_ID IS NOT NULL AND ALMACEN_ORIGEN_ID IS NULL     AND ALMACEN_DESTINO_ID IS NULL)
  );

CREATE INDEX IDX_MSP_VENTAS_PRODS_ALM_ORG ON MSP_VENTAS_PRODUCTOS (ALMACEN_ORIGEN_ID);
CREATE INDEX IDX_MSP_VENTAS_PRODS_ALM_DST ON MSP_VENTAS_PRODUCTOS (ALMACEN_DESTINO_ID);

-- ─── 5) MSP_VENTAS_COMBOS: CANTIDAD + ALMACEN_ORIGEN_ID / ALMACEN_DESTINO_ID ──
ALTER TABLE MSP_VENTAS_COMBOS ADD CANTIDAD NUMERIC(10,4);
ALTER TABLE MSP_VENTAS_COMBOS ADD ALMACEN_ORIGEN_ID  INTEGER;
ALTER TABLE MSP_VENTAS_COMBOS ADD ALMACEN_DESTINO_ID INTEGER;

UPDATE MSP_VENTAS_COMBOS c
   SET CANTIDAD           = 1,
       ALMACEN_ORIGEN_ID  = (SELECT v.ALMACEN_ORIGEN_ID  FROM MSP_VENTAS v WHERE v.ID = c.VENTA_ID),
       ALMACEN_DESTINO_ID = (SELECT v.ALMACEN_DESTINO_ID FROM MSP_VENTAS v WHERE v.ID = c.VENTA_ID);

ALTER TABLE MSP_VENTAS_COMBOS ALTER COLUMN CANTIDAD           SET NOT NULL;
ALTER TABLE MSP_VENTAS_COMBOS ALTER COLUMN ALMACEN_ORIGEN_ID  SET NOT NULL;
ALTER TABLE MSP_VENTAS_COMBOS ALTER COLUMN ALMACEN_DESTINO_ID SET NOT NULL;

ALTER TABLE MSP_VENTAS_COMBOS
  ADD CONSTRAINT CK_MSP_VENTAS_COMBOS_CANTIDAD_POS CHECK (CANTIDAD > 0);

CREATE INDEX IDX_MSP_VENTAS_COMBOS_ALM_ORG ON MSP_VENTAS_COMBOS (ALMACEN_ORIGEN_ID);
CREATE INDEX IDX_MSP_VENTAS_COMBOS_ALM_DST ON MSP_VENTAS_COMBOS (ALMACEN_DESTINO_ID);

-- ─── 6) MSP_VENTAS: drop ALMACEN_ORIGEN_ID / ALMACEN_DESTINO_ID ──────────────
DROP INDEX IDX_MSP_VENTAS_ALMACEN_ORG;
ALTER TABLE MSP_VENTAS DROP ALMACEN_ORIGEN_ID;
ALTER TABLE MSP_VENTAS DROP ALMACEN_DESTINO_ID;

-- ─── 7) Registrar la migración como aplicada ────────────────────────────────
INSERT INTO MSP_MIGRATIONS (ID, NAME, APPLIED_AT)
VALUES (3, '000003_ventas_staging_refactor', CURRENT_TIMESTAMP);

COMMIT;
