-- Reverse de 000005: regresa las columnas a ISO8859_1.
-- ADVERTENCIA: si la DB tiene rows con caracteres fuera del rango ISO8859_1
-- (em-dash, emoji, kanji, etc.), este DOWN puede fallar o truncar — Firebird
-- decide qué hacer con bytes no mapeables. Sólo úsalo si tienes seguridad de
-- la data actual o estás en dev con un snapshot fresco.

ALTER TABLE MSP_VENTAS ALTER COLUMN NOMBRE_CLIENTE     TYPE VARCHAR(200) CHARACTER SET ISO8859_1;
ALTER TABLE MSP_VENTAS ALTER COLUMN AVAL_O_RESPONSABLE TYPE VARCHAR(200) CHARACTER SET ISO8859_1;
ALTER TABLE MSP_VENTAS ALTER COLUMN CALLE              TYPE VARCHAR(300) CHARACTER SET ISO8859_1;
ALTER TABLE MSP_VENTAS ALTER COLUMN NUMERO_EXTERIOR    TYPE VARCHAR(20)  CHARACTER SET ISO8859_1;
ALTER TABLE MSP_VENTAS ALTER COLUMN COLONIA            TYPE VARCHAR(120) CHARACTER SET ISO8859_1;
ALTER TABLE MSP_VENTAS ALTER COLUMN POBLACION          TYPE VARCHAR(120) CHARACTER SET ISO8859_1;
ALTER TABLE MSP_VENTAS ALTER COLUMN CIUDAD             TYPE VARCHAR(120) CHARACTER SET ISO8859_1;
ALTER TABLE MSP_VENTAS ALTER COLUMN NOTA               TYPE VARCHAR(500) CHARACTER SET ISO8859_1;
ALTER TABLE MSP_VENTAS ALTER COLUMN CANCEL_REASON      TYPE VARCHAR(500) CHARACTER SET ISO8859_1;

ALTER TABLE MSP_VENTAS_COMBOS     ALTER COLUMN NOMBRE_COMBO     TYPE VARCHAR(200) CHARACTER SET ISO8859_1;
ALTER TABLE MSP_VENTAS_PRODUCTOS  ALTER COLUMN ARTICULO         TYPE VARCHAR(200) CHARACTER SET ISO8859_1;
ALTER TABLE MSP_VENTAS_VENDEDORES ALTER COLUMN VENDEDOR_NOMBRE  TYPE VARCHAR(200) CHARACTER SET ISO8859_1;
ALTER TABLE MSP_VENTAS_IMAGENES   ALTER COLUMN DESCRIPCION      TYPE VARCHAR(200) CHARACTER SET ISO8859_1;

ALTER TABLE MSP_USUARIOS ALTER COLUMN NOMBRE       TYPE VARCHAR(200) CHARACTER SET ISO8859_1;
ALTER TABLE MSP_ROLES    ALTER COLUMN NOMBRE       TYPE VARCHAR(50)  CHARACTER SET ISO8859_1;
ALTER TABLE MSP_ROLES    ALTER COLUMN DESCRIPCION  TYPE VARCHAR(255) CHARACTER SET ISO8859_1;
ALTER TABLE MSP_PERMISOS ALTER COLUMN DESCRIPCION  TYPE VARCHAR(255) CHARACTER SET ISO8859_1;
ALTER TABLE MSP_PERMISOS ALTER COLUMN CATEGORIA    TYPE VARCHAR(30)  CHARACTER SET ISO8859_1;

DELETE FROM MSP_MIGRATIONS WHERE ID = 5;

COMMIT;
