-- Revert 000025: drop TX_ID indices on MSP_PAGOS_VENTAS and MSP_SALDOS_VENTAS.

DROP INDEX IDX_MSP_PAGOS_VENTAS_TX_ID;
COMMIT;

DROP INDEX IDX_MSP_SALDOS_VENTAS_TX_ID;
COMMIT;

DELETE FROM MSP_MIGRATIONS WHERE ID = 25;
COMMIT;
