ALTER TABLE MSP_AN_WINBACK_CANDIDATOS DROP MONTO_PROX_PAGO;
ALTER TABLE MSP_AN_WINBACK_CANDIDATOS DROP FECHA_PROX_PAGO;
ALTER TABLE MSP_AN_WINBACK_CANDIDATOS DROP PCT_PAGOS_A_TIEMPO;
ALTER TABLE MSP_AN_WINBACK_CANDIDATOS DROP DIAS_ATRASO_PROM;
ALTER TABLE MSP_AN_WINBACK_CANDIDATOS DROP CADENCIA_DIAS;
ALTER TABLE MSP_AN_WINBACK_CANDIDATOS DROP NUM_PAGOS;

DELETE FROM MSP_MIGRATIONS WHERE ID = 37;
COMMIT;
