-- ============================================================================
-- Migración 000001: AUTH (usuarios, roles, permisos)
-- ============================================================================
-- Crea:
--   - MSP_MIGRATIONS (tracker de migraciones aplicadas)
--   - MSP_USUARIOS
--   - MSP_ROLES
--   - MSP_PERMISOS
--   - MSP_USUARIOS_ROLES (junction multi-rol)
--   - MSP_ROLES_PERMISOS (junction rol→permisos)
--
-- Target: Firebird 4 (database de Microsip — agregamos nuestras tablas con
--         prefijo MSP_ para no chocar con las nativas).
-- ============================================================================

-- ─── Tracker de migraciones ────────────────────────────────────────────────
CREATE TABLE MSP_MIGRATIONS (
  ID            INTEGER NOT NULL,
  NAME          VARCHAR(200) CHARACTER SET ASCII NOT NULL,
  APPLIED_AT    TIMESTAMP NOT NULL,

  CONSTRAINT PK_MSP_MIGRATIONS PRIMARY KEY (ID)
);

-- ─── Usuarios ──────────────────────────────────────────────────────────────
CREATE TABLE MSP_USUARIOS (
  ID              CHAR(36) CHARACTER SET ASCII NOT NULL,
  FIREBASE_UID    VARCHAR(128) CHARACTER SET ASCII NOT NULL,
  EMAIL           VARCHAR(255) CHARACTER SET ASCII NOT NULL,
  NOMBRE          VARCHAR(200) CHARACTER SET ISO8859_1 NOT NULL,
  TELEFONO        VARCHAR(30)  CHARACTER SET ASCII,
  ALMACEN_ID      INTEGER,
  ACTIVO          BOOLEAN NOT NULL,
  CREATED_AT      TIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP NOT NULL,
  CREATED_BY      CHAR(36) CHARACTER SET ASCII NOT NULL,
  UPDATED_BY      CHAR(36) CHARACTER SET ASCII NOT NULL,

  CONSTRAINT PK_MSP_USUARIOS PRIMARY KEY (ID),
  CONSTRAINT UQ_MSP_USUARIOS_FIREBASE_UID UNIQUE (FIREBASE_UID),
  CONSTRAINT UQ_MSP_USUARIOS_EMAIL        UNIQUE (EMAIL),
  CONSTRAINT FK_MSP_USUARIOS_CREATED_BY   FOREIGN KEY (CREATED_BY) REFERENCES MSP_USUARIOS (ID),
  CONSTRAINT FK_MSP_USUARIOS_UPDATED_BY   FOREIGN KEY (UPDATED_BY) REFERENCES MSP_USUARIOS (ID)
);

CREATE INDEX IDX_MSP_USUARIOS_ALMACEN ON MSP_USUARIOS (ALMACEN_ID);
CREATE INDEX IDX_MSP_USUARIOS_ACTIVO  ON MSP_USUARIOS (ACTIVO);

-- ─── Roles ─────────────────────────────────────────────────────────────────
CREATE TABLE MSP_ROLES (
  ID            CHAR(36) CHARACTER SET ASCII NOT NULL,
  NOMBRE        VARCHAR(50)  CHARACTER SET ISO8859_1 NOT NULL,
  DESCRIPCION   VARCHAR(255) CHARACTER SET ISO8859_1,
  INMUTABLE     BOOLEAN NOT NULL,
  ACTIVO        BOOLEAN NOT NULL,
  CREATED_AT    TIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP NOT NULL,
  CREATED_BY    CHAR(36) CHARACTER SET ASCII NOT NULL,
  UPDATED_BY    CHAR(36) CHARACTER SET ASCII NOT NULL,

  CONSTRAINT PK_MSP_ROLES PRIMARY KEY (ID),
  CONSTRAINT UQ_MSP_ROLES_NOMBRE       UNIQUE (NOMBRE),
  CONSTRAINT FK_MSP_ROLES_CREATED_BY   FOREIGN KEY (CREATED_BY) REFERENCES MSP_USUARIOS (ID),
  CONSTRAINT FK_MSP_ROLES_UPDATED_BY   FOREIGN KEY (UPDATED_BY) REFERENCES MSP_USUARIOS (ID)
);

CREATE INDEX IDX_MSP_ROLES_ACTIVO ON MSP_ROLES (ACTIVO);

-- ─── Permisos (catálogo, sincronizado desde código Go al arrancar) ─────────
CREATE TABLE MSP_PERMISOS (
  CODIGO        VARCHAR(60)  CHARACTER SET ASCII NOT NULL,
  DESCRIPCION   VARCHAR(255) CHARACTER SET ISO8859_1 NOT NULL,
  CATEGORIA     VARCHAR(30)  CHARACTER SET ISO8859_1 NOT NULL,

  CONSTRAINT PK_MSP_PERMISOS PRIMARY KEY (CODIGO)
);

CREATE INDEX IDX_MSP_PERMISOS_CATEGORIA ON MSP_PERMISOS (CATEGORIA);

-- ─── Junction: qué roles tiene cada usuario (multi-rol) ────────────────────
CREATE TABLE MSP_USUARIOS_ROLES (
  USUARIO_ID    CHAR(36) CHARACTER SET ASCII NOT NULL,
  ROL_ID        CHAR(36) CHARACTER SET ASCII NOT NULL,
  CREATED_AT    TIMESTAMP NOT NULL,
  CREATED_BY    CHAR(36) CHARACTER SET ASCII NOT NULL,

  CONSTRAINT PK_MSP_USUARIOS_ROLES         PRIMARY KEY (USUARIO_ID, ROL_ID),
  CONSTRAINT FK_MSP_USUARIOS_ROLES_USR     FOREIGN KEY (USUARIO_ID) REFERENCES MSP_USUARIOS (ID),
  CONSTRAINT FK_MSP_USUARIOS_ROLES_ROL     FOREIGN KEY (ROL_ID)     REFERENCES MSP_ROLES    (ID),
  CONSTRAINT FK_MSP_USUARIOS_ROLES_CREAT   FOREIGN KEY (CREATED_BY) REFERENCES MSP_USUARIOS (ID)
);

CREATE INDEX IDX_MSP_USUARIOS_ROLES_ROL ON MSP_USUARIOS_ROLES (ROL_ID);

-- ─── Junction: qué permisos tiene cada rol ─────────────────────────────────
CREATE TABLE MSP_ROLES_PERMISOS (
  ROL_ID            CHAR(36)    CHARACTER SET ASCII NOT NULL,
  PERMISO_CODIGO    VARCHAR(60) CHARACTER SET ASCII NOT NULL,
  CREATED_AT        TIMESTAMP NOT NULL,
  CREATED_BY        CHAR(36) CHARACTER SET ASCII NOT NULL,

  CONSTRAINT PK_MSP_ROLES_PERMISOS         PRIMARY KEY (ROL_ID, PERMISO_CODIGO),
  CONSTRAINT FK_MSP_ROLES_PERMISOS_ROL     FOREIGN KEY (ROL_ID)         REFERENCES MSP_ROLES    (ID),
  CONSTRAINT FK_MSP_ROLES_PERMISOS_PERMISO FOREIGN KEY (PERMISO_CODIGO) REFERENCES MSP_PERMISOS (CODIGO),
  CONSTRAINT FK_MSP_ROLES_PERMISOS_CREAT   FOREIGN KEY (CREATED_BY)     REFERENCES MSP_USUARIOS (ID)
);

CREATE INDEX IDX_MSP_ROLES_PERMISOS_PERMISO ON MSP_ROLES_PERMISOS (PERMISO_CODIGO);

-- ─── Registrar la migración como aplicada ──────────────────────────────────
INSERT INTO MSP_MIGRATIONS (ID, NAME, APPLIED_AT)
VALUES (1, '000001_create_auth_tables', CURRENT_TIMESTAMP);

COMMIT;
