-- Down for 000051_grant_msp_tables_to_microsip_users
-- Revokes the PUBLIC grants added in the up migration.

REVOKE SELECT ON MSP_PAGOS_RECIBIDOS FROM PUBLIC;
REVOKE SELECT, INSERT, UPDATE, DELETE ON MSP_PAGOS_VENTAS FROM PUBLIC;
REVOKE SELECT, INSERT, UPDATE, DELETE ON MSP_SALDOS_VENTAS FROM PUBLIC;
REVOKE SELECT, INSERT, UPDATE, DELETE ON MSP_PAGOS_CHANGELOG FROM PUBLIC;
REVOKE SELECT, INSERT, UPDATE, DELETE ON MSP_SALDOS_CHANGELOG FROM PUBLIC;
REVOKE SELECT, INSERT, UPDATE, DELETE ON MSP_SALDOS_ERRORS FROM PUBLIC;
COMMIT;

DELETE FROM MSP_MIGRATIONS WHERE ID = 51;
COMMIT;
