-- ============================================================================
-- Rollback de la migración 000002: VENTAS
-- ============================================================================
-- ⚠️  DESTRUCTIVO. Borra todas las ventas y sus líneas/combos/vendedores/
--    imágenes. Asegúrate de tener backup antes de correrlo en prod.
-- ============================================================================

DROP INDEX IDX_MSP_VENTAS_IMAGENES_STORAGE;
DROP INDEX IDX_MSP_VENTAS_IMAGENES_VENTA;
DROP TABLE MSP_VENTAS_IMAGENES;

DROP INDEX IDX_MSP_VENTAS_VENDEDORES_EMAIL;
DROP INDEX IDX_MSP_VENTAS_VENDEDORES_USUARIO;
DROP INDEX IDX_MSP_VENTAS_VENDEDORES_VENTA;
DROP TABLE MSP_VENTAS_VENDEDORES;

DROP INDEX IDX_MSP_VENTAS_PRODUCTOS_COMBO;
DROP INDEX IDX_MSP_VENTAS_PRODUCTOS_ARTICULO;
DROP INDEX IDX_MSP_VENTAS_PRODUCTOS_VENTA;
DROP TABLE MSP_VENTAS_PRODUCTOS;

DROP INDEX IDX_MSP_VENTAS_COMBOS_VENTA;
DROP TABLE MSP_VENTAS_COMBOS;

DROP INDEX IDX_MSP_VENTAS_CANCELED_AT;
DROP INDEX IDX_MSP_VENTAS_TIPO_VENTA;
DROP INDEX IDX_MSP_VENTAS_ZONA_CLIENTE;
DROP INDEX IDX_MSP_VENTAS_ALMACEN_ORG;
DROP INDEX IDX_MSP_VENTAS_CREATED_BY;
DROP INDEX IDX_MSP_VENTAS_FECHA_VENTA;
DROP TABLE MSP_VENTAS;

DELETE FROM MSP_MIGRATIONS WHERE ID = 2;

COMMIT;
