-- ============================================================================
-- Migración 000008: tablas de configuración del mapeo "aplicar venta"
-- ============================================================================
-- Configuración EDITABLE (sin redeploy) del mapeo MSP_VENTAS → Microsip que
-- usa POST /ventas/{id}/aplicar. Son tablas de referencia: estructura + datos
-- semilla, sin lógica en la BD (sin defaults, sin triggers; los IDs/valores
-- se insertan explícitos). Los IDs semilla provienen del spike validado contra
-- el Firebird dev (docs/microsip-aplicar-venta-spike.md, 2026-05-28) — son los
-- catálogos reales de Microsip (mismos IDs en producción, misma instalación).
--
--   MSP_CFG_ZONA_CAJA            zona del cliente → caja + cajero (por ruta)
--   MSP_CFG_FRECUENCIA_FORMA_PAGO frecuencia de pago → FORMA_DE_PAGO (lista)
--   MSP_CFG_PLAZO_CREDITO         plazo en meses   → CREDITO_EN_MESES (lista)
--   MSP_CFG_NUM_VENDEDORES        # vendedores     → NUMERO_DE_VENDEDORES (lista)
--   MSP_CFG_APLICAR               fila única: sucursal + formas de cobro
-- ============================================================================

-- ─── Tablas ──────────────────────────────────────────────────────────────────
CREATE TABLE MSP_CFG_ZONA_CAJA (
  ZONA_CLIENTE_ID INTEGER NOT NULL,
  CAJA_ID         INTEGER NOT NULL,
  CAJERO_ID       INTEGER NOT NULL,
  CONSTRAINT PK_MSP_CFG_ZONA_CAJA PRIMARY KEY (ZONA_CLIENTE_ID)
);

CREATE TABLE MSP_CFG_FRECUENCIA_FORMA_PAGO (
  FRECUENCIA       VARCHAR(15) CHARACTER SET ASCII NOT NULL,
  FORMA_DE_PAGO_ID INTEGER NOT NULL,
  CONSTRAINT PK_MSP_CFG_FREC_FP PRIMARY KEY (FRECUENCIA)
);

CREATE TABLE MSP_CFG_PLAZO_CREDITO (
  PLAZO_MESES         INTEGER NOT NULL,
  CREDITO_EN_MESES_ID INTEGER NOT NULL,
  CONSTRAINT PK_MSP_CFG_PLAZO_CREDITO PRIMARY KEY (PLAZO_MESES)
);

CREATE TABLE MSP_CFG_NUM_VENDEDORES (
  NUM_VENDEDORES          INTEGER NOT NULL,
  NUMERO_DE_VENDEDORES_ID INTEGER NOT NULL,
  CONSTRAINT PK_MSP_CFG_NUM_VENDEDORES PRIMARY KEY (NUM_VENDEDORES)
);

CREATE TABLE MSP_CFG_APLICAR (
  ID                     INTEGER NOT NULL,
  SUCURSAL_ID            INTEGER NOT NULL,
  FORMA_COBRO_CONTADO_ID INTEGER NOT NULL,
  FORMA_COBRO_CREDITO_ID INTEGER NOT NULL,
  CONSTRAINT PK_MSP_CFG_APLICAR PRIMARY KEY (ID),
  CONSTRAINT CK_MSP_CFG_APLICAR_SINGLETON CHECK (ID = 1)
);
COMMIT;

-- ─── Seed: zona → caja → cajero (44 rutas, del spike) ────────────────────────
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (12271, 21770, 22368);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (12272, 21787, 22369);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (12273, 21804, 22370);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (12274, 21821, 22371);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21500, 21838, 22372);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21501, 21855, 22373);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21502, 21872, 22374);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21503, 21908, 22375);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21504, 21925, 22376);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21505, 21942, 22377);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21549, 21959, 22378);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21550, 21976, 22379);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21551, 21993, 22380);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21552, 22010, 22381);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21553, 22027, 22382);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21554, 22044, 22383);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21555, 22061, 22384);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21556, 22078, 22385);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21557, 22095, 22386);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21558, 22112, 22387);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21559, 22129, 22388);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21561, 22164, 22390);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21562, 22181, 22391);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21563, 22198, 22392);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21564, 22215, 22393);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21565, 22232, 22394);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21567, 22266, 22396);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21568, 22283, 22397);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21569, 22300, 22398);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21570, 22317, 22399);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21571, 22334, 22400);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21572, 22351, 22401);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (50137, 50188, 50187);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (77487, 78170, 78189);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (79618, 79620, 79641);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (320085, 320864, 320881);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (843629, 841539, 841633);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (2990693, 2998592, 22389);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (3034588, 3034589, 3034611);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21560, 22147, 2998590);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (21566, 22249, 22395);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (23301, 64109, 64127);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (179174, 179199, 221644);
INSERT INTO MSP_CFG_ZONA_CAJA (ZONA_CLIENTE_ID, CAJA_ID, CAJERO_ID) VALUES (634157, 32119, 1162794);

-- ─── Seed: frecuencia → FORMA_DE_PAGO (LISTA_ATRIB_ID) ───────────────────────
INSERT INTO MSP_CFG_FRECUENCIA_FORMA_PAGO (FRECUENCIA, FORMA_DE_PAGO_ID) VALUES ('SEMANAL', 33824);
INSERT INTO MSP_CFG_FRECUENCIA_FORMA_PAGO (FRECUENCIA, FORMA_DE_PAGO_ID) VALUES ('QUINCENAL', 33825);
INSERT INTO MSP_CFG_FRECUENCIA_FORMA_PAGO (FRECUENCIA, FORMA_DE_PAGO_ID) VALUES ('MENSUAL', 33826);

-- ─── Seed: plazo meses → CREDITO_EN_MESES (LISTA_ATRIB_ID) ───────────────────
INSERT INTO MSP_CFG_PLAZO_CREDITO (PLAZO_MESES, CREDITO_EN_MESES_ID) VALUES (18, 33827);
INSERT INTO MSP_CFG_PLAZO_CREDITO (PLAZO_MESES, CREDITO_EN_MESES_ID) VALUES (12, 33828);
INSERT INTO MSP_CFG_PLAZO_CREDITO (PLAZO_MESES, CREDITO_EN_MESES_ID) VALUES (9, 33829);
INSERT INTO MSP_CFG_PLAZO_CREDITO (PLAZO_MESES, CREDITO_EN_MESES_ID) VALUES (6, 33830);

-- ─── Seed: # vendedores → NUMERO_DE_VENDEDORES (LISTA_ATRIB_ID) ───────────────
INSERT INTO MSP_CFG_NUM_VENDEDORES (NUM_VENDEDORES, NUMERO_DE_VENDEDORES_ID) VALUES (1, 47558);
INSERT INTO MSP_CFG_NUM_VENDEDORES (NUM_VENDEDORES, NUMERO_DE_VENDEDORES_ID) VALUES (2, 47559);
INSERT INTO MSP_CFG_NUM_VENDEDORES (NUM_VENDEDORES, NUMERO_DE_VENDEDORES_ID) VALUES (3, 47560);

-- ─── Seed: fila única de config ──────────────────────────────────────────────
INSERT INTO MSP_CFG_APLICAR (ID, SUCURSAL_ID, FORMA_COBRO_CONTADO_ID, FORMA_COBRO_CREDITO_ID)
VALUES (1, 225490, 67, 71);
COMMIT;

-- ─── Registro ────────────────────────────────────────────────────────────────
INSERT INTO MSP_MIGRATIONS (ID, NAME, APPLIED_AT)
VALUES (8, '000008_msp_cfg_aplicar', CURRENT_TIMESTAMP);
COMMIT;
