-- Down for 000053_grant_msp_procedures_to_microsip_users
-- Revokes the PUBLIC EXECUTE grants added in the up migration.

REVOKE EXECUTE ON PROCEDURE MSP_RECOMPUTE_PAGO FROM PUBLIC;
REVOKE EXECUTE ON PROCEDURE MSP_RECOMPUTE_SALDO_VENTA FROM PUBLIC;
COMMIT;

DELETE FROM MSP_MIGRATIONS WHERE ID = 53;
COMMIT;
