ALTER TABLE MSP_AN_WINBACK_CANDIDATOS DROP MONETARY_V_PROM;
ALTER TABLE MSP_AN_WINBACK_CANDIDATOS DROP VENTAS_MESES_DISTINTOS;
ALTER TABLE MSP_AN_WINBACK_CANDIDATOS DROP FECHA_ULTIMA_VENTA;
ALTER TABLE MSP_AN_WINBACK_CANDIDATOS DROP FECHA_PRIMER_VENTA;

DELETE FROM MSP_MIGRATIONS WHERE ID = 39;
COMMIT;
