-- ============================================================================
-- Rollback de la migración 000003: VENTAS staging refactor
-- ============================================================================
-- Restituye ALMACEN_ORIGEN_ID / ALMACEN_DESTINO_ID en MSP_VENTAS y revierte
-- los cambios en MSP_VENTAS_PRODUCTOS y MSP_VENTAS_COMBOS.
--
-- Backfill del header: usa los almacenes del primer combo o producto suelto
-- de cada venta (cualquiera de los dos basta, asumiendo que la separación
-- multi-almacén introducida por 000003 no se haya usado todavía en filas
-- existentes — si sí, este rollback colapsa la diversidad).
-- ============================================================================

-- ─── 1) Restituir ALMACEN_ORIGEN_ID / ALMACEN_DESTINO_ID en MSP_VENTAS ──────
ALTER TABLE MSP_VENTAS ADD ALMACEN_ORIGEN_ID  INTEGER;
ALTER TABLE MSP_VENTAS ADD ALMACEN_DESTINO_ID INTEGER;

-- Backfill: combos primero (siempre obligatorios después de 000003), luego
-- caemos a productos sueltos cuando la venta no tenía combos.
UPDATE MSP_VENTAS v SET
    ALMACEN_ORIGEN_ID = COALESCE(
        (SELECT MIN(c.ALMACEN_ORIGEN_ID) FROM MSP_VENTAS_COMBOS c WHERE c.VENTA_ID = v.ID),
        (SELECT MIN(p.ALMACEN_ORIGEN_ID) FROM MSP_VENTAS_PRODUCTOS p WHERE p.VENTA_ID = v.ID AND p.COMBO_ID IS NULL)
    ),
    ALMACEN_DESTINO_ID = COALESCE(
        (SELECT MIN(c.ALMACEN_DESTINO_ID) FROM MSP_VENTAS_COMBOS c WHERE c.VENTA_ID = v.ID),
        (SELECT MIN(p.ALMACEN_DESTINO_ID) FROM MSP_VENTAS_PRODUCTOS p WHERE p.VENTA_ID = v.ID AND p.COMBO_ID IS NULL)
    );

ALTER TABLE MSP_VENTAS ALTER COLUMN ALMACEN_ORIGEN_ID  SET NOT NULL;
ALTER TABLE MSP_VENTAS ALTER COLUMN ALMACEN_DESTINO_ID SET NOT NULL;

CREATE INDEX IDX_MSP_VENTAS_ALMACEN_ORG ON MSP_VENTAS (ALMACEN_ORIGEN_ID);

-- ─── 2) MSP_VENTAS_COMBOS: dropear CANTIDAD + ALMACENES ─────────────────────
DROP INDEX IDX_MSP_VENTAS_COMBOS_ALM_DST;
DROP INDEX IDX_MSP_VENTAS_COMBOS_ALM_ORG;
ALTER TABLE MSP_VENTAS_COMBOS DROP CONSTRAINT CK_VTA_CMB_CANTIDAD_POS;
ALTER TABLE MSP_VENTAS_COMBOS DROP ALMACEN_DESTINO_ID;
ALTER TABLE MSP_VENTAS_COMBOS DROP ALMACEN_ORIGEN_ID;
ALTER TABLE MSP_VENTAS_COMBOS DROP CANTIDAD;

-- ─── 3) MSP_VENTAS_PRODUCTOS: dropear ALMACENES ─────────────────────────────
DROP INDEX IDX_MSP_VENTAS_PRODS_ALM_DST;
DROP INDEX IDX_MSP_VENTAS_PRODS_ALM_ORG;
ALTER TABLE MSP_VENTAS_PRODUCTOS DROP CONSTRAINT CK_VTA_PROD_ALMACEN_PRES;
ALTER TABLE MSP_VENTAS_PRODUCTOS DROP ALMACEN_DESTINO_ID;
ALTER TABLE MSP_VENTAS_PRODUCTOS DROP ALMACEN_ORIGEN_ID;

-- ─── 4) MSP_VENTAS: dropear APPROVED_AT / APPROVED_BY ───────────────────────
ALTER TABLE MSP_VENTAS DROP CONSTRAINT CK_VTA_APPROVED_COHERENTE;
ALTER TABLE MSP_VENTAS DROP CONSTRAINT FK_MSP_VENTAS_APPROVED_BY;
ALTER TABLE MSP_VENTAS DROP APPROVED_BY;
ALTER TABLE MSP_VENTAS DROP APPROVED_AT;

-- ─── 5) MSP_VENTAS: dropear STATUS ──────────────────────────────────────────
DROP INDEX IDX_MSP_VENTAS_STATUS;
ALTER TABLE MSP_VENTAS DROP CONSTRAINT CK_MSP_VENTAS_STATUS;
ALTER TABLE MSP_VENTAS DROP STATUS;

-- ─── 6) MSP_VENTAS: dropear CLIENTE_ID ──────────────────────────────────────
DROP INDEX IDX_MSP_VENTAS_CLIENTE_ID;
ALTER TABLE MSP_VENTAS DROP CONSTRAINT FK_MSP_VENTAS_CLIENTE;
ALTER TABLE MSP_VENTAS DROP CLIENTE_ID;

-- ─── 7) Quitar la migración del registro ────────────────────────────────────
DELETE FROM MSP_MIGRATIONS WHERE ID = 3;

COMMIT;
