DROP TABLE MSP_AN_REFRESH_STATE;
COMMIT;

DROP INDEX IDX_MSP_AN_WINBACK_CAND_MONETARY;
DROP INDEX IDX_MSP_AN_WINBACK_CAND_EN_CTRL;
COMMIT;

DROP TABLE MSP_AN_WINBACK_CANDIDATOS;
COMMIT;

DELETE FROM MSP_MIGRATIONS WHERE ID = 35;
COMMIT;
