//nolint:misspell // ventas vocabulary is Spanish per project convention.
package venthttp_test

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3filter"
	"github.com/getkin/kin-openapi/routers"
	"github.com/getkin/kin-openapi/routers/gorillamux"
	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/abdimuy/msp-api/internal/auth"
	"github.com/abdimuy/msp-api/internal/ventas/infra/venthttp"
)

// The ventas module's OpenAPI contract is GENERATED by Huma from the
// registered operations and their Go DTOs — unlike the auth module, whose
// contract is the hand-written api/openapi.yaml validated by
// internal/auth/infra/authhttp/contract_test.go. api/openapi.yaml declares
// only the auth paths; no ventas path has ever appeared in it.
//
// So the document to validate against is the one the server actually serves
// at /v2/openapi.json. These tests fetch it, parse it with kin-openapi, and
// validate a real request AND a real response of PUT /v2/ventas/{id}/lineas
// against it. That is stricter than asserting the path string is present: a
// DTO field that drifts from the schema fails here.

// ─── rig ────────────────────────────────────────────────────────────────────

// contractLineasRig pairs a router mounted under /v2 (the prefix the generated
// spec advertises as its server) with the spec that same router publishes.
type contractLineasRig struct {
	router http.Handler
	spec   *openapi3.T
	routes routers.Router
}

// newContractLineasRig mounts the ventas module under /v2, fetches the
// generated OpenAPI document from the live router, and builds the kin-openapi
// route matcher over it.
func newContractLineasRig(t *testing.T, cu auth.CurrentUser) *contractLineasRig {
	t.Helper()
	svc, _, _ := testService()
	root := chi.NewRouter()
	root.Route("/v2", func(r chi.Router) {
		r.Use(planter(cu))
		venthttp.MountRouter(r, svc)
	})

	req := httptest.NewRequest(http.MethodGet, "/v2/openapi.json", nil)
	rec := httptest.NewRecorder()
	root.ServeHTTP(rec, req)
	require.Equal(t, http.StatusOK, rec.Code, "the router must publish its generated OpenAPI document")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = false
	spec, err := loader.LoadFromData(rec.Body.Bytes())
	require.NoError(t, err, "generated spec must parse")
	require.NoError(t, spec.Validate(t.Context()), "generated spec must be a valid OpenAPI document")

	routesMatcher, err := gorillamux.NewRouter(spec)
	require.NoError(t, err)

	return &contractLineasRig{router: root, spec: spec, routes: routesMatcher}
}

// contractAuthAny accepts any bearer token: the handler-level authn check is
// what these tests exercise, not the token itself.
func contractAuthAny(_ context.Context, _ *openapi3filter.AuthenticationInput) error { return nil }

// exchange validates the request against the spec (for success paths), serves
// it, then validates the response against the spec. Returns the recorder.
func (c *contractLineasRig) exchange(t *testing.T, req *http.Request, wantStatus int) *httptest.ResponseRecorder {
	t.Helper()

	route, pathParams, err := c.routes.FindRoute(req)
	require.NoError(t, err, "generated spec must declare route %s %s", req.Method, req.URL.Path)

	opts := &openapi3filter.Options{
		IncludeResponseStatus: true,
		AuthenticationFunc:    contractAuthAny,
	}

	var bodyBytes []byte
	if req.Body != nil {
		bodyBytes, err = io.ReadAll(req.Body)
		require.NoError(t, err)
		req.Body = io.NopCloser(bytes.NewReader(bodyBytes))
	}

	// Only positive paths are shape-validated on the way in — the negative
	// cases deliberately send bodies the spec rejects.
	if wantStatus >= 200 && wantStatus < 300 {
		require.NoError(t, openapi3filter.ValidateRequest(req.Context(), &openapi3filter.RequestValidationInput{
			Request: req, PathParams: pathParams, Route: route, Options: opts,
		}), "request must be valid per the generated spec")
		req.Body = io.NopCloser(bytes.NewReader(bodyBytes))
	}

	rec := httptest.NewRecorder()
	c.router.ServeHTTP(rec, req)
	require.Equal(t, wantStatus, rec.Code, rec.Body.String())

	require.NoError(t, openapi3filter.ValidateResponse(req.Context(), &openapi3filter.ResponseValidationInput{
		RequestValidationInput: &openapi3filter.RequestValidationInput{
			Request: req, PathParams: pathParams, Route: route, Options: opts,
		},
		Status:  rec.Code,
		Header:  rec.Header(),
		Body:    io.NopCloser(bytes.NewReader(rec.Body.Bytes())),
		Options: opts,
	}), "response must conform to the generated spec: status=%d body=%s", rec.Code, rec.Body.String())
	return rec
}

// seedVentaConComboOnRig creates the combo-bearing venta through the /v2
// router so the contract exchange has a target.
func seedVentaConComboOnRig(t *testing.T, c *contractLineasRig) (string, string) {
	t.Helper()
	body := validCreateBody()
	comboID := uuid.NewString()
	body.Combos = []venthttp.ComboDTO{comboDTO(comboID, "Combo Original")}
	body.Productos = []venthttp.ProductoDTO{comboChildDTO(comboID, 77)}

	req := crearVentaMultipartRequest(t, body)
	req.URL.Path = "/v2" + req.URL.Path
	rec := httptest.NewRecorder()
	c.router.ServeHTTP(rec, req)
	require.Equal(t, http.StatusCreated, rec.Code, rec.Body.String())
	var out venthttp.VentaDTO
	require.NoError(t, json.Unmarshal(rec.Body.Bytes(), &out))
	return out.ID, comboID
}

// jsonReq builds a JSON request under the /v2 prefix.
func jsonReq(t *testing.T, method, target string, body any) *http.Request {
	t.Helper()
	b, err := json.Marshal(body)
	require.NoError(t, err)
	req := httptest.NewRequest(method, target, bytes.NewReader(b))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer contract-test-token")
	return req
}

// ─── tests ──────────────────────────────────────────────────────────────────

// TestContract_Lineas_DeclaredInSpec asserts the generated document declares
// the operation with the shape callers depend on: PUT, a uuid path param, a
// required JSON body carrying BOTH collections, and a 200 response. It also
// pins that the two endpoints it supersedes are still declared — and now
// marked deprecated rather than removed.
func TestContract_Lineas_DeclaredInSpec(t *testing.T) {
	t.Parallel()
	c := newContractLineasRig(t, fullPerms(uuid.New()))

	item := c.spec.Paths.Find("/ventas/{id}/lineas")
	require.NotNil(t, item, "the generated spec must declare /ventas/{id}/lineas")
	op := item.Put
	require.NotNil(t, op, "the operation must be a PUT")
	assert.Equal(t, "reemplazar-lineas-venta", op.OperationID)
	assert.False(t, op.Deprecated, "the replacement endpoint must not be deprecated")

	require.NotNil(t, op.RequestBody)
	require.NotNil(t, op.RequestBody.Value)
	media := op.RequestBody.Value.Content.Get("application/json")
	require.NotNil(t, media, "the body must be application/json")
	schema := media.Schema.Value
	require.NotNil(t, schema)
	require.Contains(t, schema.Properties, "combos", "the body must carry combos")
	require.Contains(t, schema.Properties, "productos", "the body must carry productos")

	// Every status the handler can actually produce must be declared.
	for _, status := range []string{"200", "401", "403", "404", "409", "422"} {
		assert.NotNil(t, op.Responses.Value(status), "response %s must be declared", status)
	}

	// The superseded endpoints are still there — production runs them.
	for _, path := range []string{"/ventas/{id}/combos", "/ventas/{id}/productos"} {
		old := c.spec.Paths.Find(path)
		require.NotNil(t, old, "%s must keep existing", path)
		require.NotNil(t, old.Put)
		assert.True(t, old.Put.Deprecated, "%s must be marked deprecated, not removed", path)
	}
}

// TestContract_Lineas_RequestAndResponse_OK validates a real exchange — the
// borrar-y-crear edit — in both directions against the generated document.
func TestContract_Lineas_RequestAndResponse_OK(t *testing.T) {
	t.Parallel()
	c := newContractLineasRig(t, fullPerms(uuid.New()))
	id, viejoComboID := seedVentaConComboOnRig(t, c)

	nuevoComboID := uuid.NewString()
	require.NotEqual(t, viejoComboID, nuevoComboID)
	body := venthttp.ReemplazarLineasBody{
		Combos:    []venthttp.ComboDTO{comboDTO(nuevoComboID, "Combo Nuevo")},
		Productos: []venthttp.ProductoDTO{comboChildDTO(nuevoComboID, 99)},
	}

	rec := c.exchange(t, jsonReq(t, http.MethodPut, "/v2/ventas/"+id+"/lineas", body), http.StatusOK)

	var out venthttp.VentaDTO
	require.NoError(t, json.Unmarshal(rec.Body.Bytes(), &out))
	require.Len(t, out.Combos, 1)
	assert.Equal(t, nuevoComboID, out.Combos[0].ID)
}

// TestContract_Lineas_ErrorResponses validates that the problem-details
// documents the handler returns also conform to the declared schemas.
func TestContract_Lineas_ErrorResponses(t *testing.T) {
	t.Parallel()

	t.Run("404", func(t *testing.T) {
		t.Parallel()
		c := newContractLineasRig(t, fullPerms(uuid.New()))
		c.exchange(t, jsonReq(t, http.MethodPut, "/v2/ventas/"+uuid.NewString()+"/lineas", validLineasBody()),
			http.StatusNotFound)
	})

	t.Run("422 referencia invalida", func(t *testing.T) {
		t.Parallel()
		c := newContractLineasRig(t, fullPerms(uuid.New()))
		id, _ := seedVentaConComboOnRig(t, c)
		presente := uuid.NewString()
		body := venthttp.ReemplazarLineasBody{
			Combos: []venthttp.ComboDTO{comboDTO(presente, "Combo Presente")},
			Productos: []venthttp.ProductoDTO{
				comboChildDTO(presente, 1),
				comboChildDTO(uuid.NewString(), 2),
			},
		}
		c.exchange(t, jsonReq(t, http.MethodPut, "/v2/ventas/"+id+"/lineas", body),
			http.StatusUnprocessableEntity)
	})

	t.Run("403", func(t *testing.T) {
		t.Parallel()
		full := newContractLineasRig(t, fullPerms(uuid.New()))
		id, _ := seedVentaConComboOnRig(t, full)
		limited := newContractLineasRig(t, limitedPerms(uuid.New()))
		limited.exchange(t, jsonReq(t, http.MethodPut, "/v2/ventas/"+id+"/lineas", validLineasBody()),
			http.StatusForbidden)
	})
}
