//nolint:misspell // Microsip column names are Spanish by convention.
package invfb

import (
	"database/sql"

	"github.com/google/uuid"

	"github.com/abdimuy/msp-api/internal/inventario/domain"
	"github.com/abdimuy/msp-api/internal/platform/apperror"
	"github.com/abdimuy/msp-api/internal/platform/firebird"
)

// rowScanner is the minimal surface satisfied by both *sql.Row and *sql.Rows.
type rowScanner interface {
	Scan(dest ...any) error
}

// doctoInRaw holds the raw scanned columns of one DOCTOS_IN header row.
type doctoInRaw struct {
	doctoInID      int
	almacenID      int
	almacenDestino int
	folio          string
	fechaRaw       any
	descripcion    string
	createdAtRaw   any
	createdByRaw   string
}

// scanDoctoInRow scans one DOCTOS_IN header row.
func scanDoctoInRow(s rowScanner) (doctoInRaw, error) {
	var r doctoInRaw
	if err := s.Scan(
		&r.doctoInID, &r.almacenID, &r.almacenDestino,
		&r.folio, &r.fechaRaw, &r.descripcion,
		&r.createdAtRaw, &r.createdByRaw,
	); err != nil {
		return doctoInRaw{}, err
	}
	return r, nil
}

// doctoInDetRaw holds the raw scanned columns of one DOCTOS_IN_DET row.
type doctoInDetRaw struct {
	doctoInDetID int
	doctoInID    int
	articuloID   int
	unidadesRaw  any
}

// scanDoctoInDetRow scans one DOCTOS_IN_DET row.
func scanDoctoInDetRow(s rowScanner) (doctoInDetRaw, error) {
	var r doctoInDetRaw
	if err := s.Scan(&r.doctoInDetID, &r.doctoInID, &r.articuloID, &r.unidadesRaw); err != nil {
		return doctoInDetRaw{}, err
	}
	return r, nil
}

// assembleTraspaso builds a domain.Traspaso from a scanned DOCTOS_IN header row
// plus pre-loaded detalles and the MSP_VENTAS_TRASPASOS lookup data (ventaID,
// tipo, reversado). The doctoInID is stored on the aggregate to indicate it's
// applied.
func assembleTraspaso(
	r doctoInRaw,
	detalles []*domain.TraspasoDetalle,
	ventaID *uuid.UUID,
	tipoReverso bool,
	reversado bool,
	doctoInID int,
) (*domain.Traspaso, error) {
	createdAt, err := firebird.ScanUTCTime(r.createdAtRaw)
	if err != nil {
		return nil, err
	}
	fecha, err := firebird.ScanUTCTime(r.fechaRaw)
	if err != nil {
		return nil, err
	}
	// DOCTOS_IN.USUARIO_CREADOR is a Microsip user-name column (CHAR(31))
	// that the writer stamps with a stable service identity ("SYSDBA"), not
	// a UUID. The real CREATED_BY of the traspaso lives in
	// MSP_VENTAS_TRASPASOS.CREATED_BY for venta-linked rows — readers that
	// need it should join that lookup. Use uuid.Nil here as a placeholder
	// so we do not propagate parse errors for the Microsip column.
	_ = r.createdByRaw
	createdBy := uuid.Nil
	folio := domain.HydrateFolio(r.folio)
	id := doctoInID // we use doctoInID as the int handle; UUID is generated by app
	_ = id
	// Traspaso from Firebird doesn't have a separate UUID row; the domain
	// aggregate uses the UUID set at creation time which we don't have here.
	// We generate a deterministic placeholder — callers that need the original
	// UUID must read it from MSP_VENTAS_TRASPASOS (not stored there today).
	// For now we use uuid.Nil (the hydrate bypasses validation).
	return domain.HydrateTraspaso(domain.HydrateTraspasoParams{
		ID:             uuid.Nil,
		Folio:          folio,
		AlmacenOrigen:  r.almacenID,
		AlmacenDestino: r.almacenDestino,
		Fecha:          fecha,
		Descripcion:    r.descripcion,
		VentaID:        ventaID,
		TipoReverso:    tipoReverso,
		Reversado:      reversado,
		DoctoInID:      &doctoInID,
		Detalles:       detalles,
		CreatedAt:      createdAt,
		UpdatedAt:      createdAt, // DOCTOS_IN has no updated_at; use created_at
		CreatedBy:      createdBy,
		UpdatedBy:      createdBy, // same reason
	}), nil
}

// assembleDetalle builds a domain.TraspasoDetalle from a raw scan result.
func assembleDetalle(r doctoInDetRaw) (*domain.TraspasoDetalle, error) {
	unidades, err := firebird.ScanDecimal(r.unidadesRaw, existenciaScale)
	if err != nil {
		return nil, err
	}
	cantidad := domain.HydrateCantidad(unidades)
	return domain.HydrateDetalle(domain.HydrateDetalleParams{
		ID:         uuid.Nil, // no UUID stored in Firebird; placeholder
		ArticuloID: r.articuloID,
		Cantidad:   cantidad,
	}), nil
}

// parseUUIDCol parses a CHAR(36) column into a uuid.UUID.
func parseUUIDCol(column, raw string) (uuid.UUID, error) {
	id, err := uuid.Parse(raw)
	if err != nil {
		return uuid.Nil, apperror.NewInternal(
			"firebird_uuid_invalid",
			"uuid inválido en columna de base de datos",
		).WithSource("firebird").WithError(err).WithField("column", column).WithField("raw_value", raw)
	}
	return id, nil
}

// parseNullUUIDCol parses a nullable CHAR(36) column.
func parseNullUUIDCol(column string, raw sql.NullString) (*uuid.UUID, error) {
	if !raw.Valid {
		return nil, nil //nolint:nilnil // optional pointer pattern.
	}
	id, err := parseUUIDCol(column, raw.String)
	if err != nil {
		return nil, err
	}
	return &id, nil
}
